services:
  api:
    build:
      context: ./services/api/
      dockerfile: Dockerfile

    volumes:
      - ./services/api/:/opt/app/

    ports:
      - 8000:8000
    env_file:
      - ./envs/api.dev.env

volumes:
  redis_data:
