version: "3.9"

services:
  api:
    build:
      context: ./services/api/
      dockerfile: Dockerfile

    container_name: rag-api

    volumes:
      - ./services/api:/opt/app

    ports:
      - "8000:8000"

    env_file:
      - ./envs/api.dev.env

    extra_hosts:
      - "host.docker.internal:host-gateway"

    command: >
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload

    networks:
      - rag_network

  ui:
    build:
      context: ./services/ui/
      dockerfile: Dockerfile

    container_name: rag-ui

    volumes:
      - ./services/ui:/app

    ports:
      - "8501:8501"

    environment:
      - API_BASE_URL=http://api:8000

    depends_on:
      - api

    networks:
      - rag_network

networks:
  rag_network:
    driver: bridge
